apiVersion: v1
kind: Pod
metadata:
  name: web1
  namespace: web-apps
  labels:
    app: web1
spec:
  containers:
    - name: web1
      image: busybox
      command: ["sh", "-c", "while true; do echo Hello from App1; sleep 5; done"]
