apiVersion: v1
kind: Pod
metadata:
  name: web2
  namespace: web-apps
  labels:
    app: web2
spec:
  containers:
    - name: web2
      image: busybox
      command: ["sh", "-c", "while true; do echo Hello from App2; sleep 5; done"]
